//alert actions
export const HIDE_ALERT = "HIDE_ALERT";
export const SHOW_ALERT = "SHOW_ALERT";

//machine actions
export const ADD_MACHINE = "ADD_MACHINE";
export const ADD_MACHINE_SUCCESS = "ADD_MACHINE_SUCCESS";
export const ADD_MACHINE_ERROR = "ADD_MACHINE_ERROR";
export const START_GET_MACHINES = "START_GET_MACHINES";
export const GET_MACHINES_SUCCESS = "GET_MACHINES_SUCCESS";
export const GET_MACHINES_ERROR = "GET_MACHINES_ERROR";
export const GET_MACHINE_TO_DELETE = "GET_MACHINE_TO_DELETE";
export const MACHINE_DELETE_SUCCESS = "MACHINE_DELETE_SUCCESS";
export const MACHINE_DELETE_ERROR = "MACHINE_DELETE_ERROR";
export const GET_MACHINE = "GET_MACHINE";
export const GET_MACHINE_SUCCESS = "GET_MACHINE_SUCCESS";
export const GET_MACHINE_ERROR = "GET_MACHINE_ERROR";

//workFlow actions
export const ADD_WORK_FLOW = "ADD_WORK_FLOW";
export const ADD_WORK_FLOW_SUCCESS = "ADD_WORK_FLOW_SUCCESS";
export const ADD_WORK_FLOW_ERROR = "ADD_WORK_FLOW_ERROR";
export const START_GET_WORK_FLOWS = "START_GET_WORK_FLOWS";
export const GET_WORK_FLOWS_SUCCESS = "GET_WORK_FLOWS_SUCCESS";
export const GET_WORK_FLOWS_ERROR = "GET_WORK_FLOWS_ERROR";

//map actions
export const QUERY_MAP = "QUERY_MAP";
export const TABLE_VISIBLE_ROWS_CHANGE_MAP = "TABLE_VISIBLE_ROWS_CHANGE_MAP";
export const CHANGE_BOUNDS_MAP = "CHANGE_BOUNDS_MAP";
export const TABLE_HOVERED_ROWS_INDEX_CHANGE_MAP =
  "TABLE_HOVERED_ROWS_INDEX_CHANGE_MAP";
export const MARKER_HOVER_INDEX_CHANGE_MAP = "MARKER_HOVER_INDEX_CHANGE_MAP";
export const SHOW_POPUP_MAP = "SHOW_POPUP_MAP";
